apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aaarg-operator-rolebinding
subjects:
  - kind: ServiceAccount
    namespace: aaargcd-operator-system
    name: aaargcd-operator-controller-manager
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
