---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - aaargcd.io
  resources:
  - aapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aaargcd.io
  resources:
  - aapps/finalizers
  verbs:
  - update
- apiGroups:
  - aaargcd.io
  resources:
  - aapps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - CronJobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - ServiceAccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - RoleBindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
